services:
  www:
    build: .
    volumes:
      - ./:/var/www/html/helmet_shop
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    environment:
      - MYSQL_DATABASE=helmet_shop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306